sudo: required

services:
  - docker

before_install:
  - docker build -t fchwpo/fibo-dock-cci -f ./client/Dockerfile.dev ./client

script:
  # Run test commands
  - docker run -e CI=true fchwpo/fibo-dock-cci npm run test

after_success: # after sucess of test scripts
  # Build all production images
  - docker build -t fchwpo/fibo-dock-cci-client ./client
  - docker build -t fchwpo/fibo-dock-cci-server ./server
  - docker build -t fchwpo/fibo-dock-cci-worker ./worker
  - docker build -t fchwpo/fibo-dock-cci-nginx ./nginx
  # Login into Docker through CLI
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  # Take all this images and push them to docker hub`
  - docker push fchwpo/fibo-dock-cci-client
  - docker push fchwpo/fibo-dock-cci-server
  - docker push fchwpo/fibo-dock-cci-worker
  - docker push fchwpo/fibo-dock-cci-nginx

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "fibo-dock-cci"
  env: "FiboDockCci-env"
  bucket_name: "elasticbeanstalk-us-east-1-547273590547"
  bucket_path: "fibo-dock-cci"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY